cozycup/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
from graphene_django.views import GraphQLView


urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('resturant.urls')),
    path('custom/',include('customuser.urls')),
   path("graphql", GraphQLView.as_view(graphiql=True)),


]+static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

resturant/urls.py
from django.contrib import admin
from django.urls import path
from django.views import *
from .views import *
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth.views import LoginView
from django.contrib.auth.decorators import login_required

app_name='resturant'
urlpatterns = [
    
    path('home/',HomePage.as_view(),name='home_page'),
    path('add/menu/',AddMenu.as_view(),name='add_menu'),
    path('update/menu/<int:pk>',EditMenu.as_view(),name='edit_menu'),
    path('delete/menu/<int:pk>',DeleteMenu.as_view(),name='delete_menu'),
    path('list/',MenuList.as_view(),name='menu_list'),
    path('add/ingredient/',AddIngredient.as_view(),name='add_ingredient'),
    path('update/ingredient/<int:pk>',EditIngredient.as_view(),name='edit_ingredient'),
     path('ingredient/list/',IngredientList.as_view(),name='ingredient_list'),
       path('order/list/', OrderList.as_view(), name='order_list'),
    path('add/order/', AddOrder.as_view(), name='add_order'),
       path('add-recipe-requirement/<int:menu_item_id>/',AddRecipe.as_view(),name='add_recipe'),
        path('recipe/list/',RecipeList.as_view(),name='recipe_list'),
        path('login/',MyLogin.as_view(),name="my_login"),
        path('logout/', MyLogout.as_view(), name='logout'),
         path('password/reset', PasswordResetView.as_view(), name='password_reset'),
           path('password/change', ChangePassword.as_view(), name='password_change'),
      
        
    
]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
 

resturant/models.py
from datetime import timezone
from typing import Any
from django.db import models


class Menu(models.Model):
    name=models.CharField(max_length=20)
     
    price=models.FloatField()
    def __str__(self):
        return self.name 
   
class Purchase(models.Model):
    quantity=models.IntegerField()  
    menu_id=models.ForeignKey(Menu,on_delete=models.CASCADE)
class Ingredient(models.Model):
    
    name = models.CharField(max_length=100)
    available_qty = models.IntegerField()
    measurement_unit = models.CharField(max_length=20)
    def __str__(self):
        return f"{self.name} - {self.available_qty}"
class RecipeRequirement(models.Model):
     menu_item = models.ForeignKey(Menu, on_delete=models.CASCADE, related_name='recipe')
     ingredient = models.ForeignKey(Ingredient, on_delete=models.CASCADE)
     quantity = models.FloatField()
     def __str__(self):
        return f"{self.menu_item.name} - {self.quantity}"

class OrderItem(models.Model):
    food_item = models.ForeignKey(Menu, on_delete=models.CASCADE)
    quantity = models.IntegerField()
    table_name = models.CharField(max_length=100)
    created_at = models.DateTimeField(auto_now_add=True)
    def __str__(self):
        return f"{self.food_item.name} - {self.table_name}"


    
        
    

resturant/forms.py
# forms.py
from django import forms
from crispy_forms.helper import FormHelper  # Add this import statement
from crispy_forms.layout import Layout, Submit
from .models import *
from django.contrib.auth.forms import AuthenticationForm, UsernameField


class MenuForm(forms.ModelForm):
    class Meta:
        model = Menu
        fields = ['name', 'price',]
        context_object_name='forms'
        
        labels = {
            'Name': 'Name*',
            'Price': 'Price*',
           
        }
        widgets = {
            'name': forms.TextInput(attrs={'class': 'form-control'}),
            'price': forms.NumberInput(attrs={'class': 'form-control'}),
        }

   

class IngredientForm(forms.ModelForm):
    class Meta:
        model = Ingredient
        fields ="__all__"
   
        
    def __init__(self, *args, **kwargs):
        super(IngredientForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_method = 'post'
        self.helper.add_input(Submit('submit', 'Add Ingredient'))


# class OrderItemForm(forms.ModelForm):
#     class Meta:
#         model = OrderItem
#         fields = ['order', 'food_item', 'quantity']  # Make sure to include the 'order' field
        
class RecipeRequirementForm(forms.ModelForm):
    class Meta:
        model = RecipeRequirement
        fields = ['ingredient', 'quantity']


class RecipeForm(forms.ModelForm):
    
    class Meta:
        model = RecipeRequirement
        fields = ['ingredient', 'quantity']
class OrderItemForm(forms.ModelForm):
    
    class Meta:
        model = OrderItem
        fields = ("__all__")



class UserLogin(AuthenticationForm):
    username = UsernameField(widget=forms.TextInput(attrs={'class': 'bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500', 'placeholder': 'name@flowbite.com'}))
    password = forms.CharField(
        label=("Enter Your Password"),
        strip=False,
        widget=forms.PasswordInput(attrs={'class': 'bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500', 'placeholder': 'Your Password'}),
    )

resturant/views.py
from django.db.models import F
from django.shortcuts import render
from django.contrib.auth.views import LoginView,LogoutView,PasswordResetView,PasswordChangeView
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import get_object_or_404, redirect, render
from django.urls import reverse_lazy
from django.views import View
from django.views.generic.edit import *
from django.views.generic import ListView
from resturant.forms import *
from resturant.models import *
from django.contrib.auth.mixins import LoginRequiredMixin


class HomePage(LoginRequiredMixin, View):

    def get(self, request):
        return render(request, 'resturant/home_page.html')
class AddMenu(LoginRequiredMixin,CreateView):
    model = Menu
    form_class=MenuForm
    template_name = "resturant/add_menu.html"
    success_url=reverse_lazy('resturant:home_page')
    
class EditMenu(UpdateView):
    model = Menu
    form_class = MenuForm 
    template_name = "resturant/update_menu.html"
    success_url=reverse_lazy('resturant:home_page')
class DeleteMenu(DeleteView):
    model = Menu
    template_name = "resturant/delete_menu.html"

class MenuList(ListView):
    model = Menu
    form_class=MenuForm
    context_object_name = 'list'
    template_name='resturant/list_menu.html'
class IngredientList(ListView):
    model = Ingredient
    context_object_name = 'list'
    template_name='resturant/ingredient_list.html'
class AddIngredient(CreateView):
    model = Ingredient
    form_class=IngredientForm
    success_url=reverse_lazy('resturant:ingredient_list')
    template_name = "resturant/add_ingredient.html"
    

class EditIngredient(UpdateView):
    model = Ingredient
    form_class=IngredientForm
    template_name = "resturant/edit_ingredient.html"
    success_url=reverse_lazy('resturant:ingredient_list')

class OrderList(ListView):
    model = OrderItem
    context_object_name = 'list'
    template_name='resturant/order_list.html'
   
    
# class CreateOrder(CreateView):
#     model = OrderItem
#     form_class = OrderItemForm
#     template_name = "resturant/create_order.html"
#     success_url = reverse_lazy('resturant:order_list')
#     def form_valid(self, form):
#         # Save the order item form
#         order_item = form.save(commit=False)

#         # Save the order form separately
#         order_form = OrderForm(self.request.POST)
#         if order_form.is_valid():
#             order = order_form.save(commit=False)
#             order.save()

#             # Associate the order with the order item
#             order_item.order = order
#             order_item.save()

#         return super().form_valid(form)
   

      
    
class RecipeList(ListView):
    model = RecipeRequirement
    context_object_name = 'list'
    template_name='resturant/recipe_list.html'
class AddRecipe(CreateView):
    model = RecipeRequirement
    form_class=RecipeForm
    template_name = "resturant/add_recipe.html"
    success_url = reverse_lazy('resturant:recipe_list')
    def form_valid(self, form):
        menu_item_id = self.kwargs['menu_item_id']
        menu_item = Menu.objects.get(pk=menu_item_id)
        form.instance.menu_item = menu_item
        return super().form_valid(form)
class AddOrder(CreateView):
    model = OrderItem
    form_class = OrderItemForm
    template_name = "resturant/create_order.html"
    success_url = reverse_lazy('resturant:order_list')

    def form_valid(self, form):
        # Call the parent class's form_valid method to save the form data
        response = super().form_valid(form)

        # After saving the form data, retrieve the order ID (pk) of the created object
        order_id = self.object.pk
        
        try:
            # Retrieve the OrderItem instance with the given ID
            order_item = OrderItem.objects.get(pk=order_id)

            # Get the associated menu item
            menu_item = order_item.food_item

            # Get the recipe requirements for the menu item
            recipe_requirements = RecipeRequirement.objects.filter(menu_item=menu_item)

            # Calculate ingredient usage and update available quantity
            for requirement in recipe_requirements:
                ingredient = requirement.ingredient
                quantity_used = requirement.quantity * order_item.quantity
                ingredient.available_qty -= quantity_used
                ingredient.save()
            total_price = order_item.quantity * order_item.food_item.price
            context = {
                'total_price': total_price,
            }
                

        except OrderItem.DoesNotExist:
            # Handle the case where the OrderItem does not exist
            # For example, redirect to an error page or display an error message
            return HttpResponseRedirect('/error/')
        
        # Redirect the user to a success page
        return render(self.request, 'resturant/calculation_ingredient.html',context) 
class MyLogin(LoginView):
    authentication_form=UserLogin
    template_name="resturant/login.html"
    success_url = reverse_lazy('home_page')
class MyLogout(LogoutView):
    template_name = "resturant/logout.html"
class ResetPassword(PasswordResetView):
    template_name="resturant/password_reset.html"
class ChangePassword(PasswordChangeView):
    template_name="resturant/pasword_change.html"
    success_url = reverse_lazy('resturant:home_page')
    
    

resturant/templates/resturant/includes/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <script src="https://cdn.tailwindcss.com"></script>

</head>
<body>
     {% include "resturant/includes/header.html" %}
       
    
     {%block content%}
      {%endblock%}
     {% include "resturant/includes/footer.html" %}
</body>
</html>

resturant/templates/resturant/includes/footer.html
{%load static %}
<!DOCTYPE html>
<head>
 

</head>
<body>
    <footer class="text-gray-600 body-font">
        <div class="container px-5 py-24 mx-auto flex md:items-center lg:items-start md:flex-row md:flex-nowrap flex-wrap flex-col">
          <div class="w-64 flex-shrink-0 md:mx-0 mx-auto text-center md:text-left md:mt-0 mt-10">
            <a class="flex title-font font-medium items-center md:justify-start justify-center text-gray-900">
              <svg xmlns="http://www.w3.org/2000/svg" fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-10 h-10 text-white p-2 bg-purple-500 rounded-full" viewBox="0 0 24 24">
                <path d="M12 2L2 7l10 5 10-5-10-5zM2 17l10 5 10-5M2 12l10 5 10-5"></path>
              </svg>
              <span class="ml-3 text-xl">Tailblocks</span>
            </a>
            <p class="mt-2 text-sm text-gray-500">Air plant banjo lyft occupy retro adaptogen indego</p>
          </div>
          <div class="flex-grow flex flex-wrap md:pr-20 -mb-10 md:text-left text-center order-first">
            <div class="lg:w-1/4 md:w-1/2 w-full px-4">
              <h2 class="title-font font-medium text-gray-900 tracking-widest text-sm mb-3">CATEGORIES</h2>
              <nav class="list-none mb-10">
                <li>
                  <a class="text-gray-600 hover:text-gray-800">First Link</a>
                </li>
                <li>
                  <a class="text-gray-600 hover:text-gray-800">Second Link</a>
                </li>
                <li>
                  <a class="text-gray-600 hover:text-gray-800">Third Link</a>
                </li>
                <li>
                  <a class="text-gray-600 hover:text-gray-800">Fourth Link</a>
                </li>
              </nav>
            </div>
            <div class="lg:w-1/4 md:w-1/2 w-full px-4">
              <h2 class="title-font font-medium text-gray-900 tracking-widest text-sm mb-3">CATEGORIES</h2>
              <nav class="list-none mb-10">
                <li>
                  <a class="text-gray-600 hover:text-gray-800">First Link</a>
                </li>
                <li>
                  <a class="text-gray-600 hover:text-gray-800">Second Link</a>
                </li>
                <li>
                  <a class="text-gray-600 hover:text-gray-800">Third Link</a>
                </li>
                <li>
                  <a class="text-gray-600 hover:text-gray-800">Fourth Link</a>
                </li>
              </nav>
            </div>
            <div class="lg:w-1/4 md:w-1/2 w-full px-4">
              <h2 class="title-font font-medium text-gray-900 tracking-widest text-sm mb-3">CATEGORIES</h2>
              <nav class="list-none mb-10">
                <li>
                  <a class="text-gray-600 hover:text-gray-800">First Link</a>
                </li>
                <li>
                  <a class="text-gray-600 hover:text-gray-800">Second Link</a>
                </li>
                <li>
                  <a class="text-gray-600 hover:text-gray-800">Third Link</a>
                </li>
                <li>
                  <a class="text-gray-600 hover:text-gray-800">Fourth Link</a>
                </li>
              </nav>
            </div>
            <div class="lg:w-1/4 md:w-1/2 w-full px-4">
              <h2 class="title-font font-medium text-gray-900 tracking-widest text-sm mb-3">CATEGORIES</h2>
              <nav class="list-none mb-10">
                <li>
                  <a class="text-gray-600 hover:text-gray-800">First Link</a>
                </li>
                <li>
                  <a class="text-gray-600 hover:text-gray-800">Second Link</a>
                </li>
                <li>
                  <a class="text-gray-600 hover:text-gray-800">Third Link</a>
                </li>
                <li>
                  <a class="text-gray-600 hover:text-gray-800">Fourth Link</a>
                </li>
              </nav>
            </div>
          </div>
        </div>
        <div class="bg-gray-100">
          <div class="container mx-auto py-4 px-5 flex flex-wrap flex-col sm:flex-row">
            <p class="text-gray-500 text-sm text-center sm:text-left">© 2020 Tailblocks —
              <a href="https://twitter.com/knyttneve" rel="noopener noreferrer" class="text-gray-600 ml-1" target="_blank">@knyttneve</a>
            </p>
            <span class="inline-flex sm:ml-auto sm:mt-0 mt-2 justify-center sm:justify-start">
              <a class="text-gray-500">
                <svg fill="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-5 h-5" viewBox="0 0 24 24">
                  <path d="M18 2h-3a5 5 0 00-5 5v3H7v4h3v8h4v-8h3l1-4h-4V7a1 1 0 011-1h3z"></path>
                </svg>
              </a>
              <a class="ml-3 text-gray-500">
                <svg fill="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-5 h-5" viewBox="0 0 24 24">
                  <path d="M23 3a10.9 10.9 0 01-3.14 1.53 4.48 4.48 0 00-7.86 3v1A10.66 10.66 0 013 4s-4 9 5 13a11.64 11.64 0 01-7 2c9 5 20 0 20-11.5a4.5 4.5 0 00-.08-.83A7.72 7.72 0 0023 3z"></path>
                </svg>
              </a>
              <a class="ml-3 text-gray-500">
                <svg fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-5 h-5" viewBox="0 0 24 24">
                  <rect width="20" height="20" x="2" y="2" rx="5" ry="5"></rect>
                  <path d="M16 11.37A4 4 0 1112.63 8 4 4 0 0116 11.37zm1.5-4.87h.01"></path>
                </svg>
              </a>
              <a class="ml-3 text-gray-500">
                <svg fill="currentColor" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="0" class="w-5 h-5" viewBox="0 0 24 24">
                  <path stroke="none" d="M16 8a6 6 0 016 6v7h-4v-7a2 2 0 00-2-2 2 2 0 00-2 2v7h-4v-7a6 6 0 016-6zM2 9h4v12H2z"></path>
                  <circle cx="4" cy="4" r="2" stroke="none"></circle>
                </svg>
              </a>
            </span>
          </div>
        </div>
      </footer>
</body>
</html>

resturant/templates/resturant/includes/header.html
{%load static %}
<!DOCTYPE html>
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Document</title>
  <script src="https://cdn.tailwindcss.com"></script>

</head>
<body>
    <header class="text-gray-600 body-font">
        <div class="container mx-auto flex flex-wrap p-5 flex-col md:flex-row items-center">
          <a class="flex title-font font-medium items-center text-gray-900 mb-4 md:mb-0">
            <svg xmlns="http://www.w3.org/2000/svg" fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-10 h-10 text-white p-2 bg-indigo-500 rounded-full" viewBox="0 0 24 24">
              <path d="M12 2L2 7l10 5 10-5-10-5zM2 17l10 5 10-5M2 12l10 5 10-5"></path>
            </svg>
            <span class="ml-3 text-xl">Tailblocks</span>
          </a>
          <nav class="md:ml-auto flex flex-wrap items-center text-base justify-center">
            {% if form.errors %}
    <p>Your username and password didn't match. Please try again.</p>
    {% endif %}
    
    {% if next %}
        {% if user.is_authenticated %}
        <a class="mr-5 hover:text-gray-900" href="{% url 'resturant:my_login' %}">Logout</a>
        {% else %}
        <p>Please login to see this page.</p>
        {% endif %}
    {% endif %}
            <a class="mr-5 hover:text-gray-900" href="{% url 'resturant:password_reset' %}">Password Reset</a>

            <a class="mr-5 hover:text-gray-900" href="{% url 'resturant:password_change' %}">Password Change</a>
            <a class="mr-5 hover:text-gray-900">Fourth Link</a>
          </nav>
          <button class="inline-flex items-center bg-gray-100 border-0 py-1 px-3 focus:outline-none hover:bg-gray-200 rounded text-base mt-4 md:mt-0">Button
            <svg fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-4 h-4 ml-1" viewBox="0 0 24 24">
              <path d="M5 12h14M12 5l7 7-7 7"></path>
            </svg>
          </button>
        </div>
      </header>
</body>
</html>

resturant/templates/resturant/includes/table.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <section class="text-gray-600 body-font">
        <div class="container px-5 py-24 mx-auto">
          <div class="flex flex-wrap -m-4">
            <div class="lg:w-1/4 md:w-1/2 p-4 w-full">
              <a class="block relative h-48 rounded overflow-hidden">
                <img alt="ecommerce" class="object-cover object-center w-full h-full block" src="https://dummyimage.com/420x260">
              </a>
              <div class="mt-4">
                <h3 class="text-gray-500 text-xs tracking-widest title-font mb-1">CATEGORY</h3>
                <h2 class="text-gray-900 title-font text-lg font-medium">The Catalyzer</h2>
                <p class="mt-1">$16.00</p>
              </div>
            </div>
            <div class="lg:w-1/4 md:w-1/2 p-4 w-full">
              <a class="block relative h-48 rounded overflow-hidden">
                <img alt="ecommerce" class="object-cover object-center w-full h-full block" src="https://dummyimage.com/421x261">
              </a>
              <div class="mt-4">
                <h3 class="text-gray-500 text-xs tracking-widest title-font mb-1">CATEGORY</h3>
                <h2 class="text-gray-900 title-font text-lg font-medium">Shooting Stars</h2>
                <p class="mt-1">$21.15</p>
              </div>
            </div>
            <div class="lg:w-1/4 md:w-1/2 p-4 w-full">
              <a class="block relative h-48 rounded overflow-hidden">
                <img alt="ecommerce" class="object-cover object-center w-full h-full block" src="https://dummyimage.com/422x262">
              </a>
              <div class="mt-4">
                <h3 class="text-gray-500 text-xs tracking-widest title-font mb-1">CATEGORY</h3>
                <h2 class="text-gray-900 title-font text-lg font-medium">Neptune</h2>
                <p class="mt-1">$12.00</p>
              </div>
            </div>
            <div class="lg:w-1/4 md:w-1/2 p-4 w-full">
              <a class="block relative h-48 rounded overflow-hidden">
                <img alt="ecommerce" class="object-cover object-center w-full h-full block" src="https://dummyimage.com/423x263">
              </a>
              <div class="mt-4">
                <h3 class="text-gray-500 text-xs tracking-widest title-font mb-1">CATEGORY</h3>
                <h2 class="text-gray-900 title-font text-lg font-medium">The 400 Blows</h2>
                <p class="mt-1">$18.40</p>
              </div>
            </div>
            <div class="lg:w-1/4 md:w-1/2 p-4 w-full">
              <a class="block relative h-48 rounded overflow-hidden">
                <img alt="ecommerce" class="object-cover object-center w-full h-full block" src="https://dummyimage.com/424x264">
              </a>
              <div class="mt-4">
                <h3 class="text-gray-500 text-xs tracking-widest title-font mb-1">CATEGORY</h3>
                <h2 class="text-gray-900 title-font text-lg font-medium">The Catalyzer</h2>
                <p class="mt-1">$16.00</p>
              </div>
            </div>
            <div class="lg:w-1/4 md:w-1/2 p-4 w-full">
              <a class="block relative h-48 rounded overflow-hidden">
                <img alt="ecommerce" class="object-cover object-center w-full h-full block" src="https://dummyimage.com/425x265">
              </a>
              <div class="mt-4">
                <h3 class="text-gray-500 text-xs tracking-widest title-font mb-1">CATEGORY</h3>
                <h2 class="text-gray-900 title-font text-lg font-medium">Shooting Stars</h2>
                <p class="mt-1">$21.15</p>
              </div>
            </div>
            <div class="lg:w-1/4 md:w-1/2 p-4 w-full">
              <a class="block relative h-48 rounded overflow-hidden">
                <img alt="ecommerce" class="object-cover object-center w-full h-full block" src="https://dummyimage.com/427x267">
              </a>
              <div class="mt-4">
                <h3 class="text-gray-500 text-xs tracking-widest title-font mb-1">CATEGORY</h3>
                <h2 class="text-gray-900 title-font text-lg font-medium">Neptune</h2>
                <p class="mt-1">$12.00</p>
              </div>
            </div>
            <div class="lg:w-1/4 md:w-1/2 p-4 w-full">
              <a class="block relative h-48 rounded overflow-hidden">
                <img alt="ecommerce" class="object-cover object-center w-full h-full block" src="https://dummyimage.com/428x268">
              </a>
              <div class="mt-4">
                <h3 class="text-gray-500 text-xs tracking-widest title-font mb-1">CATEGORY</h3>
                <h2 class="text-gray-900 title-font text-lg font-medium">The 400 Blows</h2>
                <p class="mt-1">$18.40</p>
              </div>
            </div>
          </div>
        </div>
      </section>
</body>
</html>