cozycup/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
from graphene_django.views import GraphQLView


urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('resturant.urls')),
    path('custom/',include('customuser.urls')),
   path("graphql", GraphQLView.as_view(graphiql=True)),


]+static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

resturant/urls.py
from django.contrib import admin
from django.urls import path
from django.views import *
from .views import *
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth.views import LoginView
from django.contrib.auth.decorators import login_required

app_name='resturant'
urlpatterns = [
    
    path('home/',HomePage.as_view(),name='home_page'),
    path('add/menu/',AddMenu.as_view(),name='add_menu'),
    path('update/menu/<int:pk>',EditMenu.as_view(),name='edit_menu'),
    path('delete/menu/<int:pk>',DeleteMenu.as_view(),name='delete_menu'),
    path('list/',MenuList.as_view(),name='menu_list'),
    path('add/ingredient/',AddIngredient.as_view(),name='add_ingredient'),
    path('update/ingredient/<int:pk>',EditIngredient.as_view(),name='edit_ingredient'),
     path('ingredient/list/',IngredientList.as_view(),name='ingredient_list'),
       path('order/list/', OrderList.as_view(), name='order_list'),
    path('add/order/', AddOrder.as_view(), name='add_order'),
       path('add-recipe-requirement/<int:menu_item_id>/',AddRecipe.as_view(),name='add_recipe'),
        path('recipe/list/',RecipeList.as_view(),name='recipe_list'),
        path('login/',MyLogin.as_view(),name="my_login"),
        path('logout/', MyLogout.as_view(), name='logout'),
         path('password/reset', PasswordResetView.as_view(), name='password_reset'),
           path('password/change', ChangePassword.as_view(), name='password_change'),
      
        
    
]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
 

resturant/models.py
from datetime import timezone
from typing import Any
from django.db import models


class Menu(models.Model):
    name=models.CharField(max_length=20)
     
    price=models.FloatField()
    def __str__(self):
        return self.name 
   
class Purchase(models.Model):
    quantity=models.IntegerField()  
    menu_id=models.ForeignKey(Menu,on_delete=models.CASCADE)
class Ingredient(models.Model):
    
    name = models.CharField(max_length=100)
    available_qty = models.IntegerField()
    measurement_unit = models.CharField(max_length=20)
    def __str__(self):
        return f"{self.name} - {self.available_qty}"
class RecipeRequirement(models.Model):
     menu_item = models.ForeignKey(Menu, on_delete=models.CASCADE, related_name='recipe')
     ingredient = models.ForeignKey(Ingredient, on_delete=models.CASCADE)
     quantity = models.FloatField()
     def __str__(self):
        return f"{self.menu_item.name} - {self.quantity}"

class OrderItem(models.Model):
    food_item = models.ForeignKey(Menu, on_delete=models.CASCADE)
    quantity = models.IntegerField()
    table_name = models.CharField(max_length=100)
    created_at = models.DateTimeField(auto_now_add=True)
    def __str__(self):
        return f"{self.food_item.name} - {self.table_name}"


    
        
    

resturant/forms.py
# forms.py
from django import forms
from crispy_forms.helper import FormHelper  # Add this import statement
from crispy_forms.layout import Layout, Submit
from .models import *
from django.contrib.auth.forms import AuthenticationForm, UsernameField


class MenuForm(forms.ModelForm):
    class Meta:
        model = Menu
        fields = ['name', 'price',]
        context_object_name='forms'
        
        labels = {
            'Name': 'Name*',
            'Price': 'Price*',
           
        }
        widgets = {
            'name': forms.TextInput(attrs={'class': 'form-control'}),
            'price': forms.NumberInput(attrs={'class': 'form-control'}),
        }

   

class IngredientForm(forms.ModelForm):
    class Meta:
        model = Ingredient
        fields ="__all__"
   
        
    def __init__(self, *args, **kwargs):
        super(IngredientForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_method = 'post'
        self.helper.add_input(Submit('submit', 'Add Ingredient'))


# class OrderItemForm(forms.ModelForm):
#     class Meta:
#         model = OrderItem
#         fields = ['order', 'food_item', 'quantity']  # Make sure to include the 'order' field
        
class RecipeRequirementForm(forms.ModelForm):
    class Meta:
        model = RecipeRequirement
        fields = ['ingredient', 'quantity']


class RecipeForm(forms.ModelForm):
    
    class Meta:
        model = RecipeRequirement
        fields = ['ingredient', 'quantity']
class OrderItemForm(forms.ModelForm):
    
    class Meta:
        model = OrderItem
        fields = ("__all__")



class UserLogin(AuthenticationForm):
    username = UsernameField(widget=forms.TextInput(attrs={'class': 'bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500', 'placeholder': 'name@flowbite.com'}))
    password = forms.CharField(
        label=("Enter Your Password"),
        strip=False,
        widget=forms.PasswordInput(attrs={'class': 'bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500', 'placeholder': 'Your Password'}),
    )

resturant/views.py
from django.db.models import F
from django.shortcuts import render
from django.contrib.auth.views import LoginView,LogoutView,PasswordResetView,PasswordChangeView
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import get_object_or_404, redirect, render
from django.urls import reverse_lazy
from django.views import View
from django.views.generic.edit import *
from django.views.generic import ListView
from resturant.forms import *
from resturant.models import *
from django.contrib.auth.mixins import LoginRequiredMixin


class HomePage(LoginRequiredMixin, View):

    def get(self, request):
        return render(request, 'resturant/home_page.html')
class AddMenu(LoginRequiredMixin,CreateView):
    model = Menu
    form_class=MenuForm
    template_name = "resturant/add_menu.html"
    success_url=reverse_lazy('resturant:home_page')
    
class EditMenu(UpdateView):
    model = Menu
    form_class = MenuForm 
    template_name = "resturant/update_menu.html"
    success_url=reverse_lazy('resturant:home_page')
class DeleteMenu(DeleteView):
    model = Menu
    template_name = "resturant/delete_menu.html"

class MenuList(ListView):
    model = Menu
    form_class=MenuForm
    context_object_name = 'list'
    template_name='resturant/list_menu.html'
class IngredientList(ListView):
    model = Ingredient
    context_object_name = 'list'
    template_name='resturant/ingredient_list.html'
class AddIngredient(CreateView):
    model = Ingredient
    form_class=IngredientForm
    success_url=reverse_lazy('resturant:ingredient_list')
    template_name = "resturant/add_ingredient.html"
    

class EditIngredient(UpdateView):
    model = Ingredient
    form_class=IngredientForm
    template_name = "resturant/edit_ingredient.html"
    success_url=reverse_lazy('resturant:ingredient_list')

class OrderList(ListView):
    model = OrderItem
    context_object_name = 'list'
    template_name='resturant/order_list.html'
   
    
# class CreateOrder(CreateView):
#     model = OrderItem
#     form_class = OrderItemForm
#     template_name = "resturant/create_order.html"
#     success_url = reverse_lazy('resturant:order_list')
#     def form_valid(self, form):
#         # Save the order item form
#         order_item = form.save(commit=False)

#         # Save the order form separately
#         order_form = OrderForm(self.request.POST)
#         if order_form.is_valid():
#             order = order_form.save(commit=False)
#             order.save()

#             # Associate the order with the order item
#             order_item.order = order
#             order_item.save()

#         return super().form_valid(form)
   

      
    
class RecipeList(ListView):
    model = RecipeRequirement
    context_object_name = 'list'
    template_name='resturant/recipe_list.html'
class AddRecipe(CreateView):
    model = RecipeRequirement
    form_class=RecipeForm
    template_name = "resturant/add_recipe.html"
    success_url = reverse_lazy('resturant:recipe_list')
    def form_valid(self, form):
        menu_item_id = self.kwargs['menu_item_id']
        menu_item = Menu.objects.get(pk=menu_item_id)
        form.instance.menu_item = menu_item
        return super().form_valid(form)
class AddOrder(CreateView):
    model = OrderItem
    form_class = OrderItemForm
    template_name = "resturant/create_order.html"
    success_url = reverse_lazy('resturant:order_list')

    def form_valid(self, form):
        # Call the parent class's form_valid method to save the form data
        response = super().form_valid(form)

        # After saving the form data, retrieve the order ID (pk) of the created object
        order_id = self.object.pk
        
        try:
            # Retrieve the OrderItem instance with the given ID
            order_item = OrderItem.objects.get(pk=order_id)

            # Get the associated menu item
            menu_item = order_item.food_item

            # Get the recipe requirements for the menu item
            recipe_requirements = RecipeRequirement.objects.filter(menu_item=menu_item)

            # Calculate ingredient usage and update available quantity
            for requirement in recipe_requirements:
                ingredient = requirement.ingredient
                quantity_used = requirement.quantity * order_item.quantity
                ingredient.available_qty -= quantity_used
                ingredient.save()
            total_price = order_item.quantity * order_item.food_item.price
            context = {
                'total_price': total_price,
            }
                

        except OrderItem.DoesNotExist:
            # Handle the case where the OrderItem does not exist
            # For example, redirect to an error page or display an error message
            return HttpResponseRedirect('/error/')
        
        # Redirect the user to a success page
        return render(self.request, 'resturant/calculation_ingredient.html',context) 
class MyLogin(LoginView):
    authentication_form=UserLogin
    template_name="resturant/login.html"
    success_url = reverse_lazy('home_page')
class MyLogout(LogoutView):
    template_name = "resturant/logout.html"
class ResetPassword(PasswordResetView):
    template_name="resturant/password_reset.html"
class ChangePassword(PasswordChangeView):
    template_name="resturant/pasword_change.html"
    success_url = reverse_lazy('resturant:home_page')
    
    

resturant/templates/resturant/add_menu.html
{% extends "resturant/includes/base.html" %}
{% load static %}

{% block content %}
<form class="max-w-sm mx-auto bg-red-500 mt-8 p-8 rounded-lg" method="post">
    {% csrf_token %}
    <h2 class="text-2xl font-semibold">Add Menu</h2>
    <div class="mb-4">
        {{ form.name.label_tag }}
        {{ form.name }}
    </div>
    <div class="mb-4">
        {{ form.price.label_tag }}
        {{ form.price }}
    </div>
    <button type="submit" class="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline">Submit</button>
</form>

{% endblock %}
 
        

resturant/templates/resturant/add_recipe.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Create Order</title>
</head>
<body>
    <h1>Add recipe</h1>
    
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        {{ order_item_form.as_p }} 
         <!-- Render OrderItemForm fields -->
        <button type="submit">Submit</button>
    </form>
</body>
</html>

resturant/templates/resturant/calculation_ingredient.html
<h1>sucessfully added order</h1>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Menu List</title>
    <!-- Include Font Awesome CSS -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css">
</head>
<body>
    
    <h1>Food Sold</h1>
    <div class="container">
        <table class="table table-bordered">
            <thead class="thead-dark">
                <tr>
                    <th>Food Name</th>
                    <th>Quantity</th>
                    <th>Price</th>
                    <th>Total Price</th>
                    
                     
                </tr>
            </thead>
            <tbody>
                
                <tr>
                    <td>{{food_name}}</td>
                    <td>{{qty}}</td>
                    <td>{{price}}</td>
                    <td>{{total_price}}</td>
                    <td>
                         </td>
                </tr>
                
            </tbody>
        </table>
    </div>
</body>
</html>

resturant/templates/resturant/create_order.html
<form method="post" >
    {% csrf_token %}
    {{ form.as_p }}
    
    <button type="submit">Submit</button>
</form>

resturant/templates/resturant/delete_menu.html
<!-- add_menu.html -->
{% load crispy_forms_tags %}

<form method="post">
    {% csrf_token %}
    {% crispy form %}
</form>

resturant/templates/resturant/edit_ingredient.html
<!-- add_menu.html -->
{% load crispy_forms_tags %}

<form method="post">
    {% csrf_token %}
    {% crispy form %}
</form>

resturant/templates/resturant/fooditem_form.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Create Order</title>
</head>
<body>
    <h1>Add FoodItem</h1>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        {{ order_item_form.as_p }}  <!-- Render OrderItemForm fields -->
        <button type="submit">Submit</button>
    </form>
</body>
</html>

resturant/templates/resturant/home_page.html
{% extends "resturant/includes/base.html" %}
{% load static %}

{% block content %}
<section class="text-gray-600 body-font">
    <div class="container px-5 py-24 mx-auto">
        <div class="flex flex-wrap -m-4">
            <div class="lg:w-1/4 md:w-1/2 p-4 w-full">
                <a class="block relative h-48 rounded overflow-hidden">
                <img alt="ecommerce" class="object-cover object-center w-full h-full block" src="{% static 'resturant/ingredient.jpg' %}">
                </a>
                <div class="mt-4">
                    <a  href="{% url 'resturant:ingredient_list'%}">Ingredient</a>
        
                        <h3 class="text-gray-500 text-xs tracking-widest title-font mb-1">Inventory stock for Resturant</h3>
                            <h2 class="text-gray-900 title-font text-lg font-medium">Check the inventory</h2>
                    
                </div>
            </div>
            <div class="lg:w-1/4 md:w-1/2 p-4 w-full">
                <a class="block relative h-48 rounded overflow-hidden">
                <img alt="ecommerce" class="object-cover object-center w-full h-full block" src="{% static 'resturant/food_order.jpg' %}">
                </a>
                <div class="mt-4">
                    <a  href="{% url 'resturant:order_list'%}">Order</a>
        
                        <h3 class="text-gray-500 text-xs tracking-widest title-font mb-1">today income</h3>
                            <h2 class="text-gray-900 title-font text-lg font-medium">lets make order big</h2>
                    
                </div>
            </div>
            <div class="lg:w-1/4 md:w-1/2 p-4 w-full">
                <a class="block relative h-48 rounded overflow-hidden">
                <img alt="ecommerce" class="object-cover object-center w-full h-full block" src="{% static 'resturant/food_recipe.jpg' %}">
                </a>
                <div class="mt-4">
                    <a  href="{% url 'resturant:recipe_list'%}">Recipe</a>
        
                        <h3 class="text-gray-500 text-xs tracking-widest title-font mb-1">recipe for each food is diferent</h3>
                            <h2 class="text-gray-900 title-font text-lg font-medium">Lets Innovate new recipe</h2>
                    
                </div>
            </div>
            <div class="lg:w-1/4 md:w-1/2 p-4 w-full">
                <a class="block relative h-48 rounded overflow-hidden">
                <img alt="ecommerce" class="object-cover object-center w-full h-full block" src="{% static 'resturant/foodmenu.jpg' %}">
                </a>
                <div class="mt-4">
                    <a  href="{% url 'resturant:menu_list'%}">Menu</a>
        
                        <h3 class="text-gray-500 text-xs tracking-widest title-font mb-1">Today special Menu</h3>
                            <h2 class="text-gray-900 title-font text-lg font-medium">sadeko Momo</h2>
                    
                </div>
            </div>
        </div>
    </div>
</section>

{% endblock %}

resturant/templates/resturant/ingredient_list.html
<!-- menu_list.html -->
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>IngredientList</title>
    <!-- Include Font Awesome CSS -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css">
</head>
<body>
    <h1>Menu List</h1>
    <a href="{% url 'resturant:add_ingredient'%}">Add Ingredient</a>
    <div class="container">
        
        <table class="table table-bordered">
            <thead class="thead-dark">
                <tr>
                    <th>Name</th>
                    <th>Quantity</th>
                    <th>unit</th>
                    <th>Actions</th> <!-- Add column for actions -->
                </tr>
            </thead>
            <tbody>
                {% for menu in list %}
                <tr>
                    <td>{{ menu.name }}</td>
                    <td>{{ menu.available_qty }}</td>
                    <td>{{ menu.measurement_unit }}</td>
                    <td>
                        <!-- Edit icon -->
                        <a href="{% url 'resturant:edit_ingredient' menu.id %}"><i class="fas fa-edit"></i></a>
                        <!-- Delete icon -->
                        <a href="{% url 'resturant:delete_menu' menu.id %}"><i class="fas fa-trash"></i></a>
                    </td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</body>
</html>

resturant/templates/resturant/login.html
{% extends "resturant/includes/base.html" %}
{% load static %}

{% block content %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Login</title>
    <style>
        /* Add your custom CSS styling here */
        .my_class {
            /* Your custom styles for the password field */
        }
    </style>
</head>
<body>
  
    <form class="max-w-sm mx-auto bg-red-500 mt-8 p-8 rounded-lg" method="post" action="">
        {% csrf_token %}
        <h2 class="block mb-2 text-sm font-medium text-gray-900 dark:text-white">Login</h2>
        <div class="mb-5">
            <label for="username" class="block mb-2 text-sm font-medium text-gray-900 dark:text-white">Username</label>
            <input type="text" id="username" name="username" class="bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500" placeholder="name@flowbite.com" required />
        </div>
        <div class="mb-5">
            <label for="password" class="block mb-2 text-sm font-medium text-gray-900 dark:text-white">Your password</label>
            <input type="password" id="password" name="password" class="bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500" required />
        </div>
        
        <button type="submit" class="text-white bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg text-sm w-full sm:w-auto px-5 py-2.5 text-center dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800">Submit</button>
    </form>
    
</body>
</html>
{% endblock %}

resturant/templates/resturant/order_list.html
<!-- menu_list.html -->
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Menu List</title>
    <!-- Include Font Awesome CSS -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css">
</head>
<body>
    <a href="{% url 'resturant:add_order'%}"> Add Order</a>
    <h1>Order List</h1>
    <div class="container">
        <table class="table table-bordered">
            <thead class="thead-dark">
                <tr>
                    <th>Food Item</th>
                    <th>Table  Name</th>
                    <th>Created_at</th>
                    <th>Quantity</th>
                    <th>Actions</th> <!-- Add column for actions -->
                </tr>
            </thead>
            <tbody>
                {% for menu in list %}
                <tr>
                    <td>{{ menu.food_item.name }}</td>
                    <td>{{ menu.table_name }}</td>
                    <td>{{ menu.created_at }}</td>
                    <td>{{ menu.quantity }}</td>
                    <td>
                        <!-- Edit icon -->
                        <a href="{% url 'resturant:edit_menu' menu.id %}"><i class="fas fa-edit"></i></a>
                        <!-- Delete icon -->
                        <a href="{% url 'resturant:delete_menu' menu.id %}"><i class="fas fa-trash"></i></a>
                    </td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</body>
</html>

resturant/templates/resturant/pasword_change.html
{% extends "resturant/includes/base.html" %}
{% load static %}

{% block content %}
<div class="container mx-auto mt-8">
    

    <form  class="max-w-sm mx-auto bg-red-500 mt-8 p-8 rounded-lg" method="post" >
        {% csrf_token %}
        <h2 class="text-2xl font-semibold">Password Change</h2>
        <div class="mb-4">
            {{ form.old_password.label_tag }}
            {{ form.old_password }}
            {% if form.old_password.errors %}
                <p class="text-red-500">{{ form.old_password.errors }}</p>
            {% endif %}
        </div>
        <div class="mb-4">
            {{ form.new_password1.label_tag }}
            {{ form.new_password1 }}
            {% if form.new_password1.errors %}
                <p class="text-red-500">{{ form.new_password1.errors }}</p>
            {% endif %}
        </div>
        <div class="mb-4">
            {{ form.new_password2.label_tag }}
            {{ form.new_password2 }}
            {% if form.new_password2.errors %}
                <p class="text-red-500">{{ form.new_password2.errors }}</p>
            {% endif %}
        </div>
        
        <button type="submit" class="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline">Change Password</button>
    </form>
</div>
{% endblock %}

resturant/templates/resturant/recipe_list.html
<!-- menu_list.html -->
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Menu List</title>
    <!-- Include Font Awesome CSS -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css">
</head>
<body>
    <h1>Recipe List</h1>
    
    <div class="container">
        <table class="table table-bordered">
            <thead class="thead-dark">
                <tr>
                    <th>Menu Item</th>
                    
                    
                    <th>Actions</th> <!-- Add column for actions -->
                </tr>
            </thead>
            <tbody>
                {% for menu in list %}
                <tr>
                    <td>{{ menu.menu_item.name }}</td>
                  
                    <td>
                        <!-- Edit icon -->
                        <a href="{% url 'resturant:add_recipe' menu.menu_item_id %}">add Recipe</a>
                        <a href="{% url 'resturant:edit_menu' menu.id %}"><i class="fas fa-edit"></i></a>
                        <!-- Delete icon -->
                        <a href="{% url 'resturant:delete_menu' menu.id %}"><i class="fas fa-trash"></i></a>
                    </td>
                </tr>
               
                {% endfor %}
            </tbody>
        </table>
    </div>
</body>
</html>

resturant/templates/resturant/set_recipe.html
<!-- set_recipe.html -->

<!DOCTYPE html>
<html>
<head>
    <title>Set Recipe for Food Item</title>
</head>
<body>
    <h1>Set Recipe for {{ food_item.name }}</h1>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Save</button>
    </form>
</body>
</html>